### ISSUE TITLE
Windows support planned?

### ISSUE THREAD

**Issue by oscarbg** [procedural/glFast#1]
Also can you point what work must be done in order to support it? i.e. it's only a matter of changing GLX to WGL calls or uses some Linux specific system calls?

**Comment by procedural** [comment]
@oscarbg I would actually support Clang compiler on Windows, but people expect it to work with MSVC that can't compile C code, and since I have no plans to rewrite the examples in C++ I marked it as unsupported.

**Comment by oscarbg** [comment]
I have already "ported" to VS2015 and created a project.. super easy, just changing arrays with cariable size to use malloc..

**Comment by procedural** [comment]
@oscarbg can you test if MSVC is fine with changes I made just now to support Windows?

**Comment by procedural** [comment]
00 Hello Triangle should compile with VC++ now!

**Comment by oscarbg** [comment]
thanks..

**Comment by procedural** [comment]
Thanks to @nlguillemot! :)
